# Generated by Django 4.1.7 on 2023-03-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_nickname', models.CharField(max_length=45)),
                ('user_definition', models.CharField(max_length=45, null=True)),
                ('user_profile_image', models.CharField(max_length=45)),
                ('user_point_number', models.CharField(max_length=45)),
                ('is_seller', models.BigIntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_user_id', models.CharField(max_length=45)),
                ('following_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
            options={
                'db_table': 'follow',
            },
        ),
    ]
