# Generated by Django 4.1.7 on 2023-03-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_definition',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
